<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Website Maintenance</title>
<style type="text/css">
body,html,div,p,span,h3,ol,ul,li{margin:0;padding:0;}
ol,ul,li{list-style:none;}
body,html{height:100%;}
.main{width:100%; height:100%; background:#e8e8e8; font-family:"微软雅黑", "宋体";}
.con{width:565px;*width:568px;margin:0 auto;}

.result{background:#008ead;padding:110px 0 80px;}
.result h3{width:100%;border-bottom:1px solid #fff;padding-bottom:10px;margin-bottom:10px;font-size:33px;color:#fff;font-weight:bold;}
.result div{color:#e8e8e8;}
.result p{font-size:25px;}
.result ol{padding-left:25px;*padding-left:28px;}
.result ol li{list-style:decimal;font-size:20px;}

.explain{background:#e2e2e2; color:#666;font-size:12px;padding:20px 0;}
.explain .info2{margin-top:15px;}
.explain .info2 p{font-weight:bold;}
.explain .info2 ul{padding-left:15px;}
.explain .info2 li{ list-style:disc;}

.tel{padding:20px 0;color:#666;}
.tel p{font-size:16px;}
</style>
</head>

<body>
<div class="main">
  <div class="result">
    <div class="con">
        <h3>Sorry, the page you requested is under maintenance! </h3>
        <div>
            <p>This may be because:</p>
            <ol>
              <li>The page undergoing maintenance, temporarily unable to access</li>
              <li>This page is being installed</li>
            </ol>
      </div>
    </div>
  </div>
  <div class="explain">
    <div class="con">
      <div class="info1">
        <p><i>Want to help deal with?</i></p>
          <ul>
              <?php
                  if (isset($GLOBALS['report'])) :
              ?>
              <li>Report: <a href="javascript:;"><?php echo $GLOBALS['report'];?></a></li>
              <?php
                  else :
                  ?>
              <li>:( Sorry, there is no way to find help!</li>
                  <?php
                  endif;
              ?>
          </ul>
        </div>
    </div>
  </div>
</div>


</body></html>